#!/bin/bash


killall conky
sleep 2s

conky -c $HOME/.config/conky/desktop.conf &> /dev/null &
conky -c $HOME/.config/conky/top-panel.conf &> /dev/null &
conky -c $HOME/.config/conky/bottom-panel.conf &> /dev/null &



